### Introduction

This is a user's guide to navigating the Pelham Lab's ABCD metadata spreadsheet (metadata-ABCD-items.csv). The csv file contains several columns meant to help navigate the ABCD dataset while working in R or similar statistical programming languages.

| Column name           | Origin                       | Contents                                                                                                                                                                                      |
|-----------------------|------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [study]               | ABCD metadata                | the study the item is derived from (Core or N/A) \* might go ahead and delete this column                                                                                                     |
| [domain]              | ABCD metadata                | a sorting system that all ABCD 6.0 release variables were sorted into                                                                                                                         |
| [sub_domain]          | ABCD metadata                | a subsystem within domain that all ABCD 6.0 release variables were sorted into                                                                                                                |
| [source]              | ABCD metadata                | allows us to quickly tell who the respondent/subject was                                                                                                                                      |
| [table_name]          | ABCD metadata                | collections of ABCD variables that were administered and/or collected together                                                                                                                |
| [name]                | ABCD metadata and Pelham Lab | name of the variable; mostly derived from ABCD 6.0 metadata                                                                                                                                   |
| [label]               | ABCD metadata and Pelham Lab | describes the contents of the variable in more detail                                                                                                                                         |
| [has_branching_logic] | Pelham Lab                   | a yes/no indication of the presence of gating                                                                                                                                                 |
| [sensitivity]         | Pelham Lab                   | an evaluation of how sensitive the content of the variable is                                                                                                                                 |
| [plab_facet]          | Pelham Lab                   | a sorting system that all ABCD 6.0 release variables and Pelham Lab variables were sorted into                                                                                                |
| [plab_subfacet]       | Pelham Lab                   | a subsystem within domain that all ABCD 6.0 release and Pelham Lab variables were sorted into                                                                                                 |
| [alexsa_facet]        | Pelham Lab                   | utilizes the subscales from the Assessment of Liability and EXposure to Substance use and Antisocial behavior for Children (ALEXSA) assessment (Ridenour et al., 2009) to sort variables into |

### study

### domain

### sub_domain

### source

### table_name

### name

### label

### has_branching_logic

### sensitivity

### plab_facet

### plab_subfacet

### alexsa_facet
