---
title: "Introduction"
---

### **What is this website?**

This website describes a set of tools we created for developing survey-based prediction models using data from the Adolescent Brain Cognitive Development (ABCD) Study release \[6.0\]

Here are some examples of prediction models you might want to develop:

-   Predict which children ages 9-10 will develop substance use problems by age 18

-   Predict the level of depressive symptoms 12 months into the future

-   Predict the probability of school dropout in each grade of high school

There are the sorts of tasks the tools are intended to help with.

### **What do you mean by a "prediction model"?**

"Prediction models" predict a dependent variable ($Y$) from multiple independent variables ($X$s). These are alternately called "prediction algorithms," "prognostic models," "forecasting models," or "screening algorithms."

When developing these tools, the main use-case we had in mind was that in which the $X$s temporally precede the $Y$ (i.e., predicting from now into the future). However, the tools could also be used for predicting a $Y$ that is measured concurrently to the $X$s.

### **Why focus on "survey-based" predictors?**

Here, the prediction models are "survey-based" because they only use predictors ($X$s) that could be measured via a single survey question.

We exclude other measurement modalities (e.g., brain imaging, neuropsychological testing, interviewer impressions) because at present they are too expensive, time-consuming, and/or logistically challenging for widespread implementation.

It is difficult to get professionals and systems to use even basic, survey-based screening algorithms --- let alone to collect and integrate multimodal data to feed such an algorithm.

Here, we focus on relatively brief, low-burden, survey-based assessments that are suitable for widespread deployment in applied settings (e.g., schools, clinics, communities).

### **What are the "tools" you offer here?**

The tools included on this website are:

-   Code to create a tidy dataframe with 2,742 individual survey items to use as predictors ($X$s) in prediction models (one click)

-   Metadata for the 2,742 individual survey items that can be used to guide selection of which to use as predictors (e.g., to identify those measuring similar concepts)

-   A worked example with code showing the end-to-end process 

Creating and evaluating a predictive model has a few steps:

1.  Choose what to predict ($Y$)

2.  Choose the predictors ($X$s)

3.  Create an algorithm that takes values on the predictors ($X$s) as inputs and gives a score ($\hat{Y}$s) as the output

4.  Evaluate the performance of the algorithm created in #3 along a set of predictive performance metrics

*When the dataset is fixed, like ABCD, then #2 becomes the most time-consuming step.*

*The tools make it easier to create such models via some plug-and-play options.*

### **I want to create a survey-based prediction model: how do I get started?**

First, you'll need access to the ABCD Study 6.0 data --- that is only available \[directly from the NIH\].

Second, download the code repository \[abcd-itembuild\]. This code will take the ABCD Study 6.0 data and create a tidy dataframe with individual survey items ready to plug into a predictive model.

Third, see the \[worked example\] for a start-to-finish illustration that developed a screening measure for prospective prediction of substances use outcomes from late childhood (ages 9-10) to mid-adolescence (ages 15-16). This page also has utility functions to automate steps in the process (e.g., \[example\]).

Here are some references we recommend on creating and evaluation prediction models:

Steyerberg, E. W., & Harrell, F. E. (2016). Prediction models need appropriate internal, internal--external, and external validation. Journal of Clinical Epidemiology, 69, 245--247. https://doi.org/10.1016/j.jclinepi.2015.04.005

Japkowicz, N., & Shah, M. (2011). Evaluating Learning Algorithms: A Classification Perspective. Cambridge University Press.

Hemingway, H., Croft, P., Perel, P., Hayden, J. A., Abrams, K., Timmis, A., Briggs, A., Udumyan, R., Moons, K. G. M., Steyerberg, E. W., Roberts, I., Schroter, S., Altman, D. G., & Riley, R. D. (2013). Prognosis research strategy (PROGRESS) 1: A framework for researching clinical outcomes. BMJ, 346, e5595. <https://doi.org/10.1136/bmj.e5595> 

Riley, R. D., Hayden, J. A., Steyerberg, E. W., Moons, K. G. M., Abrams, K., Kyzas, P. A., Malats, N., Briggs, A., Schroter, S., Altman, D. G., Hemingway, H., & Group,  for the P. (2013). Prognosis research strategy (PROGRESS) 2: Prognostic factor research. PLOS Medicine, 10(2), e1001380. <https://doi.org/10.1371/journal.pmed.1001380> 

Steyerberg, E. W., Moons, K. G. M., Windt, D. A. van der, Hayden, J. A., Perel, P., Schroter, S., 

Riley, R. D., Hemingway, H., Altman, D. G., & Group,  for the P. (2013). Prognosis research strategy (PROGRESS) 3: Prognostic model research. PLOS Medicine, 10(2), e1001381. <https://doi.org/10.1371/journal.pmed.1001381>

Hingorani, A. D., Windt, D. A. van der, Riley, R. D., Abrams, K., Moons, K. G. M., Steyerberg, E. W., Schroter, S., Sauerbrei, W., Altman, D. G., & Hemingway, H. (2013). Prognosis research strategy (PROGRESS) 4: Stratified medicine research. BMJ, 346, e5793. <https://doi.org/10.1136/bmj.e5793>
