### Introduction

This is a user's guide to navigating the Pelham Lab's ABCD metadata spreadsheet (metadata-ABCD-items.csv). The csv file contains several columns meant to help navigate the ABCD dataset while working in R or similar statistical programming languages.

| Column                | Origin                       | Contents                                                                                                                                                                                      |
|----------------------------|-----------------|--------------------------------|
| [study]               | ABCD metadata                | the study the item is derived from (Core or N/A) \* might go ahead and delete this column                                                                                                     |
| [domain]              | ABCD metadata                | a sorting system that all ABCD 6.0 release variables were sorted into                                                                                                                         |
| [sub_domain]          | ABCD metadata                | a subsystem within domain that all ABCD 6.0 release variables were sorted into                                                                                                                |
| [source]              | ABCD metadata                | allows us to quickly tell who the respondent/subject was                                                                                                                                      |
| [table_name]          | ABCD metadata                | collections of ABCD variables that were administered and/or collected together                                                                                                                |
| [name]                | ABCD metadata and Pelham Lab | name of the variable; mostly derived from ABCD 6.0 metadata; some created by the Pelham Lab through manipulation                                                                              |
| [label]               | ABCD metadata and Pelham Lab | describes the contents of the variable in more detail                                                                                                                                         |
| [has_branching_logic] | Pelham Lab                   | a yes/no indication of the presence of gating                                                                                                                                                 |
| [sensitivity]         | Pelham Lab                   | an evaluation of how sensitive the content of the variable is                                                                                                                                 |
| [plab_facet]          | Pelham Lab                   | a sorting system that all ABCD 6.0 release variables and Pelham Lab variables were sorted into                                                                                                |
| [plab_subfacet]       | Pelham Lab                   | a subsystem within domain that all ABCD 6.0 release and Pelham Lab variables were sorted into                                                                                                 |
| [alexsa_facet]        | Pelham Lab                   | utilizes the subscales from the Assessment of Liability and EXposure to Substance use and Antisocial behavior for Children (ALEXSA) assessment (Ridenour et al., 2009) to sort variables into |

: Please **scroll horizontally** to view the entirety of the table

Pelham Lab Metadata (metadata-ABCD-items.csv) consists only of variables considered viable items for use in a predictive screening battery. The full metadata containing all columns from the ABCD 6.0 metadata release AND all columns the Pelham Lab used to sort and recode variables can be found [here](https://www.rd.usda.gov/sites/default/files/pdf-sample_0.pdf).

Pelham Lab research assistants evaluated the entirety of the metadata from the ABCD 6.0 release under the supervision of Dr. William Pelham III. Variables were first evaluated on the basis of viability as a question on a survey. If a variable could be a survey question, it was then evaluated on the following: a) administration of the variable in the core study (such that all eligible ABCD participants could have completed the variable) , b) administration of the variable happening outside of the eligibility screener, c) if gating is present, the variable's ability to be combined with the gating question(s) to produce a straightforward single question with a single set of responses with a monotonic relationship with the outcomes , and d) any other reason that would make presenting the variable on a predictive screening battery difficult. More information on how we created the bespoke metadata can be found [here](https://docs.google.com/document/d/1wit57vQvdoEeb6oLyM0x9mYwy2F0ez0y_4foyNkmhvY/edit?tab=t.0).

### study

### domain

### sub_domain

### source

### table_name

### name

### label

### has_branching_logic

### sensitivity

### plab_facet

### plab_subfacet

### alexsa_facet
